# Generated by Django 2.1.7 on 2019-04-11 03:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name_field',
            field=models.CharField(default='', help_text="Blog's name field", max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
