# Generated by Django 2.1.7 on 2019-04-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photos/None/no-img.jpg', upload_to='photos/'),
        ),
    ]
