# Generated by Django 2.1.7 on 2019-04-16 08:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190416_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='portrait/default.png', upload_to=blog.models.PathAndRename('portrait/')),
        ),
    ]
