# Generated by Django 2.1.7 on 2019-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
    ]
