# Generated by Django 2.1.7 on 2019-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190416_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(default=-1),
        ),
    ]
