# Generated by Django 2.1.7 on 2019-04-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
